#!/usr/bin/env bash
# generate_inventory.sh — Generates Ansible inventory from live Vagrant SSH config
# Re-run this script after 'vagrant up' if VMs change.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INVENTORY_FILE="$SCRIPT_DIR/inventory.ini"

# Move to the Vagrantfile directory (one level up from ansible/)
VAGRANT_DIR="$(dirname "$SCRIPT_DIR")"

echo "Reading SSH config from Vagrant in: $VAGRANT_DIR"
cd "$VAGRANT_DIR"

get_ssh_value() {
  local vm="$1"
  local key="$2"
  vagrant ssh-config "$vm" 2>/dev/null | awk "/^  $key / {print \$2}"
}

declare -A HOSTS
HOSTS=(
  [controlplane]="control_nodes"
  [node01]="workers"
  [node02]="workers"
  [services]="service_nodes"
)

declare -A PORTS
declare -A KEYS

echo "Fetching SSH configs..."
for vm in controlplane node01 node02 services; do
  PORTS[$vm]=$(get_ssh_value "$vm" "Port")
  KEYS[$vm]=$(get_ssh_value "$vm" "IdentityFile")
  echo "  $vm -> port=${PORTS[$vm]} key=${KEYS[$vm]}"
done

cat > "$INVENTORY_FILE" <<EOF
# Auto-generated by generate_inventory.sh — $(date)
# Re-run this script after 'vagrant up' if VMs change.

[control_nodes]
controlplane ansible_host=127.0.0.1 ansible_port=${PORTS[controlplane]} ansible_user=vagrant ansible_python_interpreter=/usr/bin/python3 ansible_ssh_private_key_file=${KEYS[controlplane]}

[workers]
node01 ansible_host=127.0.0.1 ansible_port=${PORTS[node01]} ansible_user=vagrant ansible_python_interpreter=/usr/bin/python3 ansible_ssh_private_key_file=${KEYS[node01]}
node02 ansible_host=127.0.0.1 ansible_port=${PORTS[node02]} ansible_user=vagrant ansible_python_interpreter=/usr/bin/python3 ansible_ssh_private_key_file=${KEYS[node02]}

[k8s_cluster:children]
control_nodes
workers

[service_nodes]
services ansible_host=127.0.0.1 ansible_port=${PORTS[services]} ansible_user=vagrant ansible_python_interpreter=/usr/bin/python3 ansible_ssh_private_key_file=${KEYS[services]}

[all:children]
k8s_cluster
service_nodes
EOF

echo ""
echo "inventory.ini generated at: $INVENTORY_FILE"
